### ISSUE TITLE
when selection mode is disabled, on keylist configuration

### ISSUE THREAD

**Issue by mthebaud** [lifecompanionaac/lifecompanion#327]
```
        ... 28 common frames omitted
[09:41:41.706][WARN ][JavaFX Application Thread][ErrorHandlingController] A error is reported with a exception dialog
java.lang.NullPointerException: Cannot invoke "org.lifecompanion.model.api.categorizedelement.useevent.UseEventListenerI.fireEvent(org.lifecompanion.model.api.categorizedelement.useevent.UseEventGeneratorI, java.util.List, java.util.function.Consumer)" because "this.useEventListener" is null
        at org.lifecompanion.app@1.6.1/org.lifecompanion.model.impl.categorizedelement.useevent.available.MouseButtonPressedEventGenerator.lambda$modeStart$0(Unknown Source)
        at org.lifecompanion.app@1.6.1/org.lifecompanion.controller.selectionmode.SelectionModeController.fireMouseEventForListener(Unknown Source)
        at org.lifecompanion.app@1.6.1/org.lifecompanion.controller.selectionmode.SelectionModeController.globalMouseEvent(Unknown Source)
        at org.lifecompanion.app@1.6.1/org.lifecompanion.ui.configurationcomponent.usemode.UseModeConfigurationDisplayer.lambda$addMouseListener$2(Unknown Source)
        at javafx.base@18.0.2/com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(Unknown Source)
        at javafx.base@18.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(Unknown Source)
        at javafx.base@18.0.2/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(Unknown Source)
        at javafx.base@18.0.2/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(Unknown Source)
        at javafx.base@18.0.2/com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(Unknown Source)
        at javafx.base@18.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base@18.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base@18.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base@18.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base@18.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
        at javafx.base@18.0.2/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
        at javafx.base@18.0.2/javafx.event.Event.fireEvent(Unknown Source)
        at javafx.graphics@18.0.2/javafx.scene.Scene$MouseHandler.process(Unknown Source)
        at javafx.graphics@18.0.2/javafx.scene.Scene.processMouseEvent(Unknown Source)
        at javafx.graphics@18.0.2/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
        at javafx.graphics@18.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
        at javafx.graphics@18.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at javafx.graphics@18.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
        at javafx.graphics@18.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
        at javafx.graphics@18.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
        at javafx.graphics@18.0.2/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
        at javafx.graphics@18.0.2/com.sun.glass.ui.View.notifyMouse(Unknown Source)
        at javafx.graphics@18.0.2/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics@18.0.2/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by mthebaud** [comment]
Previous configuration was using a OnMousePressedEventGenerator
